package eapli.base.ordermanagement.domain;

public enum OrderState {
    REGISTERED,PAYMENT_PENDING,TO_BE_PREPARED,BEING_PREPARED,READY_FOR_PACKAGING,READY_FOR_CARRIER_DISPATCHING,DISPATCHED,DELIVERED_BY_CARRIED,RECEIVED_BY_COSTUMER
}
