#!/bin/bash
STOREPASS="forgotten"
for ENT in digitalTwinServer_J twinClient1_J twinClient2_J twinClient3_J twinClient4_J ; do
 rm -f ${ENT}.jks ${ENT}.pem
 echo -e "${ENT}\nDEI\nISEP\nPORTO\nPORTO\nPT\nyes" | keytool -genkey -v -alias ${ENT} -keyalg RSA -keysize 2048 \
	-validity 365 -keystore ${ENT}.jks -storepass ${STOREPASS}
 keytool -exportcert -alias ${ENT} -keystore ${ENT}.jks -storepass ${STOREPASS} -rfc -file ${ENT}.pem
done
####
echo "Creating trust relations"
### IMPORTING TRUSTED CERTIFICATES
### (The server trusts all clients except for twinClient4_J)
### (Every client trusts digitalTwinServer_J)
for ENT in twinClient_J twinClient2_J twinClient3_J; do
 echo "yes"|keytool -import -alias ${ENT} -keystore digitalTwinServer_J.jks -file ${ENT}.pem -storepass ${STOREPASS}
 echo "yes"|keytool -import -alias digitalTwinServer_J -keystore ${ENT}.jks -file digitalTwinServer_J.pem -storepass ${STOREPASS}
done
echo "yes"|keytool -import -alias digitalTwinServer_J -keystore twinClient4_J.jks -file digitalTwinServer_J.pem -storepass ${STOREPASS}
echo "############################################################################"
keytool -list -keystore digitalTwinServer_J.jks -storepass ${STOREPASS}
echo "############################################################################"
echo "WARNING: For testing, twinClient4_J is not added to the list of authorized clients"
echo "############################################################################"
#######
